# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gy7i3Bb8K7jLiagw3AlwwKJhbH7tRabl
"""

!pip install easyocr

import easyocr

listImage = ['Placa-FQF9941', 
             'Placa-HQW5678', 
             'Placa-Mercosul-ABC1B34', 
             'Placa-Mercosul-BRA0S17', 
             'Placa-Mercosul-BRA2O20', 
             'Placa-Mercosul-POX4G21',
             'Placa-Mercosul-POX4G21-So-Placa', 
             'Placa-Mercosul-QRM7E33', 
             'Placa-Mercosul-RHA0A01',
             'Placa-QOZ1774']
imageFormat = 'jpg'
imageRootUrl = 'https://raw.githubusercontent.com/douglas-rittono/license-plate-recognition-ml-project/main/Images/'

reader = easyocr.Reader(['pt'])

for item in listImage:
  image_url = f'{ imageRootUrl }{ item }.{ imageFormat }'
  result = reader.readtext(image_url)
  for itemValue in result:
    txt = itemValue[1].replace(' ', '')
    print(txt)